general_cfg:
  model_path: outputs/object_detector/train/yolo11n/weights/best.pt
  input_video_path: acquisition_system/inputs/853889-hd_1920_1080_25fps.mp4
  name: 853889-hd_1920_1080_25fps
  save_annotated_video: true
  show_annotated_frames: false
  log_to_file: true

track_cfg:
  tracker: bytetrack.yaml
  conf: 0.55
  iou: 0.7
  device: 0
 
sqam_cfg:
  n: 75
  p: 10
  x: 5
  t: 3
  d: 15
  v: 0.025
  camera_dist: 920
  diagrams: true
  
